version: '3'
services:
#  application:
#    build: .
#    ports:
#      - "8000:8000"

#  postgres:
#    image: postgres
#    ports:
#      - '5432:5432'
#    environment:
#      POSTGRES_PASSWORD: hui
#      POSTGRES_USER: mslavoshevskiy
#      POSTGRES_DB: favorite

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    ports:
      - '3000:3000'
    networks:
      - grafana-net

  graphite_statsd:
    image: graphiteapp/docker-graphite-statsd:latest
    container_name: graphite-statsd
    ports:
      - '8125:8125/udp'
      - '80:80'
    networks:
      - grafana-net

networks:
  grafana-net:
